# Generated by Django 4.2.5 on 2023-11-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_school_file_course_alter_student_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doubt',
        ),
    ]
