# Generated by Django 4.2.5 on 2023-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_doubt'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='study_materials',
            field=models.ManyToManyField(blank=True, related_name='students', to='school_app.school_file'),
        ),
    ]
