# Generated by Django 4.2.5 on 2023-12-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_remove_student_study_materials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doubt',
        ),
    ]
