# Generated by Django 4.2.5 on 2023-12-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_feedback_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
