# Generated by Django 4.2.5 on 2023-12-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0011_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('feedback', models.TextField()),
                ('admin_reply', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('roll_number', 'name')},
            },
        ),
    ]
