# Generated by Django 4.2.5 on 2023-12-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0012_feedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
    ]
